/*
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class T2AProposalProvider extends AbstractT2AProposalProvider {
}
