/**
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.t2A;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DOM</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uma.es.angular.t2a.t2A.T2APackage#getDOM()
 * @model
 * @generated
 */
public interface DOM extends EDOM
{
} // DOM
