/**
 * generated by Xtext 2.31.0
 */
package uma.es.angular.t2a.t2A;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EDOM</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uma.es.angular.t2a.t2A.T2APackage#getEDOM()
 * @model
 * @generated
 */
public interface EDOM extends Element
{
} // EDOM
