/**
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.t2A;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance EDOM Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uma.es.angular.t2a.t2A.InstanceEDOMFeature#getEdoms <em>Edoms</em>}</li>
 *   <li>{@link uma.es.angular.t2a.t2A.InstanceEDOMFeature#getString <em>String</em>}</li>
 * </ul>
 *
 * @see uma.es.angular.t2a.t2A.T2APackage#getInstanceEDOMFeature()
 * @model
 * @generated
 */
public interface InstanceEDOMFeature extends EObject
{
  /**
   * Returns the value of the '<em><b>Edoms</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edoms</em>' reference.
   * @see #setEdoms(EDOM)
   * @see uma.es.angular.t2a.t2A.T2APackage#getInstanceEDOMFeature_Edoms()
   * @model
   * @generated
   */
  EDOM getEdoms();

  /**
   * Sets the value of the '{@link uma.es.angular.t2a.t2A.InstanceEDOMFeature#getEdoms <em>Edoms</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Edoms</em>' reference.
   * @see #getEdoms()
   * @generated
   */
  void setEdoms(EDOM value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see uma.es.angular.t2a.t2A.T2APackage#getInstanceEDOMFeature_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link uma.es.angular.t2a.t2A.InstanceEDOMFeature#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // InstanceEDOMFeature
