/**
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.t2A;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uma.es.angular.t2a.t2A.T2AFactory
 * @model kind="package"
 * @generated
 */
public interface T2APackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "t2A";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.es.uma/angular/t2a/T2A";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "t2A";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  T2APackage eINSTANCE = uma.es.angular.t2a.t2A.impl.T2APackageImpl.init();

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.RootImpl <em>Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.RootImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getRoot()
   * @generated
   */
  int ROOT = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.ElementImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.PageImpl <em>Page</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.PageImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getPage()
   * @generated
   */
  int PAGE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Page Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__PAGE_FEATURES = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Page</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.EDOMImpl <em>EDOM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.EDOMImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getEDOM()
   * @generated
   */
  int EDOM = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDOM__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDOM__FEATURES = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>EDOM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDOM_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.DOMImpl <em>DOM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.DOMImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getDOM()
   * @generated
   */
  int DOM = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOM__NAME = EDOM__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOM__FEATURES = EDOM__FEATURES;

  /**
   * The number of structural features of the '<em>DOM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOM_FEATURE_COUNT = EDOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.CompImpl <em>Comp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.CompImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getComp()
   * @generated
   */
  int COMP = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP__NAME = EDOM__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP__FEATURES = EDOM__FEATURES;

  /**
   * The number of structural features of the '<em>Comp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_FEATURE_COUNT = EDOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.InstanciaEDOMImpl <em>Instancia EDOM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.InstanciaEDOMImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getInstanciaEDOM()
   * @generated
   */
  int INSTANCIA_EDOM = 6;

  /**
   * The feature id for the '<em><b>Instancia</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCIA_EDOM__INSTANCIA = 0;

  /**
   * The feature id for the '<em><b>Insfeatures</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCIA_EDOM__INSFEATURES = 1;

  /**
   * The number of structural features of the '<em>Instancia EDOM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCIA_EDOM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.InstanceEDOMFeatureImpl <em>Instance EDOM Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.InstanceEDOMFeatureImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getInstanceEDOMFeature()
   * @generated
   */
  int INSTANCE_EDOM_FEATURE = 7;

  /**
   * The feature id for the '<em><b>Edoms</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCE_EDOM_FEATURE__EDOMS = 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCE_EDOM_FEATURE__STRING = 1;

  /**
   * The number of structural features of the '<em>Instance EDOM Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCE_EDOM_FEATURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.PageFeatureImpl <em>Page Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.PageFeatureImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getPageFeature()
   * @generated
   */
  int PAGE_FEATURE = 8;

  /**
   * The feature id for the '<em><b>Instancia EDOM</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FEATURE__INSTANCIA_EDOM = 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FEATURE__STRING = 1;

  /**
   * The number of structural features of the '<em>Page Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FEATURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uma.es.angular.t2a.t2A.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uma.es.angular.t2a.t2A.impl.FeatureImpl
   * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 9;

  /**
   * The feature id for the '<em><b>Instancia EDOM</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__INSTANCIA_EDOM = 0;

  /**
   * The feature id for the '<em><b>Allow Slot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__ALLOW_SLOT = 1;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__STRING = 2;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.Root <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root</em>'.
   * @see uma.es.angular.t2a.t2A.Root
   * @generated
   */
  EClass getRoot();

  /**
   * Returns the meta object for the containment reference list '{@link uma.es.angular.t2a.t2A.Root#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see uma.es.angular.t2a.t2A.Root#getElements()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Elements();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see uma.es.angular.t2a.t2A.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link uma.es.angular.t2a.t2A.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uma.es.angular.t2a.t2A.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.Page <em>Page</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page</em>'.
   * @see uma.es.angular.t2a.t2A.Page
   * @generated
   */
  EClass getPage();

  /**
   * Returns the meta object for the containment reference list '{@link uma.es.angular.t2a.t2A.Page#getPageFeatures <em>Page Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Page Features</em>'.
   * @see uma.es.angular.t2a.t2A.Page#getPageFeatures()
   * @see #getPage()
   * @generated
   */
  EReference getPage_PageFeatures();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.EDOM <em>EDOM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EDOM</em>'.
   * @see uma.es.angular.t2a.t2A.EDOM
   * @generated
   */
  EClass getEDOM();

  /**
   * Returns the meta object for the containment reference list '{@link uma.es.angular.t2a.t2A.EDOM#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see uma.es.angular.t2a.t2A.EDOM#getFeatures()
   * @see #getEDOM()
   * @generated
   */
  EReference getEDOM_Features();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.DOM <em>DOM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DOM</em>'.
   * @see uma.es.angular.t2a.t2A.DOM
   * @generated
   */
  EClass getDOM();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.Comp <em>Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comp</em>'.
   * @see uma.es.angular.t2a.t2A.Comp
   * @generated
   */
  EClass getComp();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.InstanciaEDOM <em>Instancia EDOM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instancia EDOM</em>'.
   * @see uma.es.angular.t2a.t2A.InstanciaEDOM
   * @generated
   */
  EClass getInstanciaEDOM();

  /**
   * Returns the meta object for the reference '{@link uma.es.angular.t2a.t2A.InstanciaEDOM#getInstancia <em>Instancia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Instancia</em>'.
   * @see uma.es.angular.t2a.t2A.InstanciaEDOM#getInstancia()
   * @see #getInstanciaEDOM()
   * @generated
   */
  EReference getInstanciaEDOM_Instancia();

  /**
   * Returns the meta object for the containment reference list '{@link uma.es.angular.t2a.t2A.InstanciaEDOM#getInsfeatures <em>Insfeatures</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Insfeatures</em>'.
   * @see uma.es.angular.t2a.t2A.InstanciaEDOM#getInsfeatures()
   * @see #getInstanciaEDOM()
   * @generated
   */
  EReference getInstanciaEDOM_Insfeatures();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.InstanceEDOMFeature <em>Instance EDOM Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instance EDOM Feature</em>'.
   * @see uma.es.angular.t2a.t2A.InstanceEDOMFeature
   * @generated
   */
  EClass getInstanceEDOMFeature();

  /**
   * Returns the meta object for the reference '{@link uma.es.angular.t2a.t2A.InstanceEDOMFeature#getEdoms <em>Edoms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Edoms</em>'.
   * @see uma.es.angular.t2a.t2A.InstanceEDOMFeature#getEdoms()
   * @see #getInstanceEDOMFeature()
   * @generated
   */
  EReference getInstanceEDOMFeature_Edoms();

  /**
   * Returns the meta object for the attribute '{@link uma.es.angular.t2a.t2A.InstanceEDOMFeature#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see uma.es.angular.t2a.t2A.InstanceEDOMFeature#getString()
   * @see #getInstanceEDOMFeature()
   * @generated
   */
  EAttribute getInstanceEDOMFeature_String();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.PageFeature <em>Page Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Feature</em>'.
   * @see uma.es.angular.t2a.t2A.PageFeature
   * @generated
   */
  EClass getPageFeature();

  /**
   * Returns the meta object for the containment reference '{@link uma.es.angular.t2a.t2A.PageFeature#getInstanciaEDOM <em>Instancia EDOM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instancia EDOM</em>'.
   * @see uma.es.angular.t2a.t2A.PageFeature#getInstanciaEDOM()
   * @see #getPageFeature()
   * @generated
   */
  EReference getPageFeature_InstanciaEDOM();

  /**
   * Returns the meta object for the attribute '{@link uma.es.angular.t2a.t2A.PageFeature#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see uma.es.angular.t2a.t2A.PageFeature#getString()
   * @see #getPageFeature()
   * @generated
   */
  EAttribute getPageFeature_String();

  /**
   * Returns the meta object for class '{@link uma.es.angular.t2a.t2A.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see uma.es.angular.t2a.t2A.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the containment reference '{@link uma.es.angular.t2a.t2A.Feature#getInstanciaEDOM <em>Instancia EDOM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instancia EDOM</em>'.
   * @see uma.es.angular.t2a.t2A.Feature#getInstanciaEDOM()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_InstanciaEDOM();

  /**
   * Returns the meta object for the attribute '{@link uma.es.angular.t2a.t2A.Feature#isAllowSlot <em>Allow Slot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Allow Slot</em>'.
   * @see uma.es.angular.t2a.t2A.Feature#isAllowSlot()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_AllowSlot();

  /**
   * Returns the meta object for the attribute '{@link uma.es.angular.t2a.t2A.Feature#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see uma.es.angular.t2a.t2A.Feature#getString()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_String();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  T2AFactory getT2AFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.RootImpl <em>Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.RootImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getRoot()
     * @generated
     */
    EClass ROOT = eINSTANCE.getRoot();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__ELEMENTS = eINSTANCE.getRoot_Elements();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.ElementImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.PageImpl <em>Page</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.PageImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getPage()
     * @generated
     */
    EClass PAGE = eINSTANCE.getPage();

    /**
     * The meta object literal for the '<em><b>Page Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE__PAGE_FEATURES = eINSTANCE.getPage_PageFeatures();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.EDOMImpl <em>EDOM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.EDOMImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getEDOM()
     * @generated
     */
    EClass EDOM = eINSTANCE.getEDOM();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDOM__FEATURES = eINSTANCE.getEDOM_Features();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.DOMImpl <em>DOM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.DOMImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getDOM()
     * @generated
     */
    EClass DOM = eINSTANCE.getDOM();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.CompImpl <em>Comp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.CompImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getComp()
     * @generated
     */
    EClass COMP = eINSTANCE.getComp();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.InstanciaEDOMImpl <em>Instancia EDOM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.InstanciaEDOMImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getInstanciaEDOM()
     * @generated
     */
    EClass INSTANCIA_EDOM = eINSTANCE.getInstanciaEDOM();

    /**
     * The meta object literal for the '<em><b>Instancia</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTANCIA_EDOM__INSTANCIA = eINSTANCE.getInstanciaEDOM_Instancia();

    /**
     * The meta object literal for the '<em><b>Insfeatures</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTANCIA_EDOM__INSFEATURES = eINSTANCE.getInstanciaEDOM_Insfeatures();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.InstanceEDOMFeatureImpl <em>Instance EDOM Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.InstanceEDOMFeatureImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getInstanceEDOMFeature()
     * @generated
     */
    EClass INSTANCE_EDOM_FEATURE = eINSTANCE.getInstanceEDOMFeature();

    /**
     * The meta object literal for the '<em><b>Edoms</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTANCE_EDOM_FEATURE__EDOMS = eINSTANCE.getInstanceEDOMFeature_Edoms();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTANCE_EDOM_FEATURE__STRING = eINSTANCE.getInstanceEDOMFeature_String();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.PageFeatureImpl <em>Page Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.PageFeatureImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getPageFeature()
     * @generated
     */
    EClass PAGE_FEATURE = eINSTANCE.getPageFeature();

    /**
     * The meta object literal for the '<em><b>Instancia EDOM</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE_FEATURE__INSTANCIA_EDOM = eINSTANCE.getPageFeature_InstanciaEDOM();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE_FEATURE__STRING = eINSTANCE.getPageFeature_String();

    /**
     * The meta object literal for the '{@link uma.es.angular.t2a.t2A.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uma.es.angular.t2a.t2A.impl.FeatureImpl
     * @see uma.es.angular.t2a.t2A.impl.T2APackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Instancia EDOM</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__INSTANCIA_EDOM = eINSTANCE.getFeature_InstanciaEDOM();

    /**
     * The meta object literal for the '<em><b>Allow Slot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__ALLOW_SLOT = eINSTANCE.getFeature_AllowSlot();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__STRING = eINSTANCE.getFeature_String();

  }

} //T2APackage
