/*
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractT2AValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uma.es.angular.t2a.t2A.T2APackage.eINSTANCE);
		return result;
	}
}
