/**
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.t2A.impl;

import org.eclipse.emf.ecore.EClass;

import uma.es.angular.t2a.t2A.Comp;
import uma.es.angular.t2a.t2A.T2APackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comp</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CompImpl extends EDOMImpl implements Comp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T2APackage.Literals.COMP;
  }

} //CompImpl
