/**
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.t2A.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uma.es.angular.t2a.t2A.Comp;
import uma.es.angular.t2a.t2A.Feature;
import uma.es.angular.t2a.t2A.StyleClass;
import uma.es.angular.t2a.t2A.T2APackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comp</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uma.es.angular.t2a.t2A.impl.CompImpl#getHostclasses <em>Hostclasses</em>}</li>
 *   <li>{@link uma.es.angular.t2a.t2A.impl.CompImpl#getSclassesOnline <em>Sclasses Online</em>}</li>
 *   <li>{@link uma.es.angular.t2a.t2A.impl.CompImpl#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompImpl extends EDOMImpl implements Comp
{
  /**
   * The cached value of the '{@link #getHostclasses() <em>Hostclasses</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHostclasses()
   * @generated
   * @ordered
   */
  protected EList<StyleClass> hostclasses;

  /**
   * The cached value of the '{@link #getSclassesOnline() <em>Sclasses Online</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSclassesOnline()
   * @generated
   * @ordered
   */
  protected EList<String> sclassesOnline;

  /**
   * The cached value of the '{@link #getFeatures() <em>Features</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeatures()
   * @generated
   * @ordered
   */
  protected EList<Feature> features;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T2APackage.Literals.COMP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StyleClass> getHostclasses()
  {
    if (hostclasses == null)
    {
      hostclasses = new EObjectResolvingEList<StyleClass>(StyleClass.class, this, T2APackage.COMP__HOSTCLASSES);
    }
    return hostclasses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getSclassesOnline()
  {
    if (sclassesOnline == null)
    {
      sclassesOnline = new EDataTypeEList<String>(String.class, this, T2APackage.COMP__SCLASSES_ONLINE);
    }
    return sclassesOnline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Feature> getFeatures()
  {
    if (features == null)
    {
      features = new EObjectContainmentEList<Feature>(Feature.class, this, T2APackage.COMP__FEATURES);
    }
    return features;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T2APackage.COMP__FEATURES:
        return ((InternalEList<?>)getFeatures()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T2APackage.COMP__HOSTCLASSES:
        return getHostclasses();
      case T2APackage.COMP__SCLASSES_ONLINE:
        return getSclassesOnline();
      case T2APackage.COMP__FEATURES:
        return getFeatures();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T2APackage.COMP__HOSTCLASSES:
        getHostclasses().clear();
        getHostclasses().addAll((Collection<? extends StyleClass>)newValue);
        return;
      case T2APackage.COMP__SCLASSES_ONLINE:
        getSclassesOnline().clear();
        getSclassesOnline().addAll((Collection<? extends String>)newValue);
        return;
      case T2APackage.COMP__FEATURES:
        getFeatures().clear();
        getFeatures().addAll((Collection<? extends Feature>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T2APackage.COMP__HOSTCLASSES:
        getHostclasses().clear();
        return;
      case T2APackage.COMP__SCLASSES_ONLINE:
        getSclassesOnline().clear();
        return;
      case T2APackage.COMP__FEATURES:
        getFeatures().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T2APackage.COMP__HOSTCLASSES:
        return hostclasses != null && !hostclasses.isEmpty();
      case T2APackage.COMP__SCLASSES_ONLINE:
        return sclassesOnline != null && !sclassesOnline.isEmpty();
      case T2APackage.COMP__FEATURES:
        return features != null && !features.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sclassesOnline: ");
    result.append(sclassesOnline);
    result.append(')');
    return result.toString();
  }

} //CompImpl
