/**
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.t2A.impl;

import org.eclipse.emf.ecore.EClass;

import uma.es.angular.t2a.t2A.DOM;
import uma.es.angular.t2a.t2A.T2APackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>DOM</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DOMImpl extends EDOMImpl implements DOM
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DOMImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T2APackage.Literals.DOM;
  }

} //DOMImpl
