/**
 * generated by Xtext 2.31.0
 */
package uma.es.angular.t2a.t2A.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import uma.es.angular.t2a.t2A.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class T2AFactoryImpl extends EFactoryImpl implements T2AFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static T2AFactory init()
  {
    try
    {
      T2AFactory theT2AFactory = (T2AFactory)EPackage.Registry.INSTANCE.getEFactory(T2APackage.eNS_URI);
      if (theT2AFactory != null)
      {
        return theT2AFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new T2AFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public T2AFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case T2APackage.ROOT: return createRoot();
      case T2APackage.ELEMENT: return createElement();
      case T2APackage.PAGE: return createPage();
      case T2APackage.EDOM: return createEDOM();
      case T2APackage.STYLE_GLOBAL: return createStyleGlobal();
      case T2APackage.STYLE_ONLINE: return createStyleOnline();
      case T2APackage.JS_ONLINE: return createJSOnline();
      case T2APackage.STYLE_CLASS: return createStyleClass();
      case T2APackage.SATTRIBUTE_AND_VALUE: return createSAttributeAndValue();
      case T2APackage.DOM: return createDOM();
      case T2APackage.COMP: return createComp();
      case T2APackage.INSTANCIA_EDOM: return createInstanciaEDOM();
      case T2APackage.INSTANCE_EDOM_FEATURE: return createInstanceEDOMFeature();
      case T2APackage.PAGE_FEATURE: return createPageFeature();
      case T2APackage.FEATURE: return createFeature();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Root createRoot()
  {
    RootImpl root = new RootImpl();
    return root;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Element createElement()
  {
    ElementImpl element = new ElementImpl();
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Page createPage()
  {
    PageImpl page = new PageImpl();
    return page;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EDOM createEDOM()
  {
    EDOMImpl edom = new EDOMImpl();
    return edom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StyleGlobal createStyleGlobal()
  {
    StyleGlobalImpl styleGlobal = new StyleGlobalImpl();
    return styleGlobal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StyleOnline createStyleOnline()
  {
    StyleOnlineImpl styleOnline = new StyleOnlineImpl();
    return styleOnline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSOnline createJSOnline()
  {
    JSOnlineImpl jsOnline = new JSOnlineImpl();
    return jsOnline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StyleClass createStyleClass()
  {
    StyleClassImpl styleClass = new StyleClassImpl();
    return styleClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SAttributeAndValue createSAttributeAndValue()
  {
    SAttributeAndValueImpl sAttributeAndValue = new SAttributeAndValueImpl();
    return sAttributeAndValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DOM createDOM()
  {
    DOMImpl dom = new DOMImpl();
    return dom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comp createComp()
  {
    CompImpl comp = new CompImpl();
    return comp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanciaEDOM createInstanciaEDOM()
  {
    InstanciaEDOMImpl instanciaEDOM = new InstanciaEDOMImpl();
    return instanciaEDOM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanceEDOMFeature createInstanceEDOMFeature()
  {
    InstanceEDOMFeatureImpl instanceEDOMFeature = new InstanceEDOMFeatureImpl();
    return instanceEDOMFeature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PageFeature createPageFeature()
  {
    PageFeatureImpl pageFeature = new PageFeatureImpl();
    return pageFeature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Feature createFeature()
  {
    FeatureImpl feature = new FeatureImpl();
    return feature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public T2APackage getT2APackage()
  {
    return (T2APackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static T2APackage getPackage()
  {
    return T2APackage.eINSTANCE;
  }

} //T2AFactoryImpl
