/*
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class T2ARuntimeModule extends AbstractT2ARuntimeModule {
}
