/*
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class T2AStandaloneSetup extends T2AStandaloneSetupGenerated {

	public static void doSetup() {
		new T2AStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
