/*
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class T2AGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.Root");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAppNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAppNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAppNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cAppNameAssignment_1.eContents().get(0);
		private final Assignment cGlobalStyleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cGlobalStyleStyleGlobalParserRuleCall_2_0 = (RuleCall)cGlobalStyleAssignment_2.eContents().get(0);
		private final Assignment cStyleOnlineAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStyleOnlineStyleOnlineParserRuleCall_3_0 = (RuleCall)cStyleOnlineAssignment_3.eContents().get(0);
		private final Assignment cJsOnlineAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cJsOnlineJSOnlineParserRuleCall_4_0 = (RuleCall)cJsOnlineAssignment_4.eContents().get(0);
		private final Assignment cElementsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cElementsElementParserRuleCall_5_0 = (RuleCall)cElementsAssignment_5.eContents().get(0);
		
		//Root:
		//    'AppName:' appName=STRING
		//    (globalStyle=StyleGlobal)?
		//    (styleOnline=StyleOnline)?
		//    (jsOnline=JSOnline)?
		//    elements+=Element+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'AppName:' appName=STRING
		//(globalStyle=StyleGlobal)?
		//(styleOnline=StyleOnline)?
		//(jsOnline=JSOnline)?
		//elements+=Element+
		public Group getGroup() { return cGroup; }
		
		//'AppName:'
		public Keyword getAppNameKeyword_0() { return cAppNameKeyword_0; }
		
		//appName=STRING
		public Assignment getAppNameAssignment_1() { return cAppNameAssignment_1; }
		
		//STRING
		public RuleCall getAppNameSTRINGTerminalRuleCall_1_0() { return cAppNameSTRINGTerminalRuleCall_1_0; }
		
		//(globalStyle=StyleGlobal)?
		public Assignment getGlobalStyleAssignment_2() { return cGlobalStyleAssignment_2; }
		
		//StyleGlobal
		public RuleCall getGlobalStyleStyleGlobalParserRuleCall_2_0() { return cGlobalStyleStyleGlobalParserRuleCall_2_0; }
		
		//(styleOnline=StyleOnline)?
		public Assignment getStyleOnlineAssignment_3() { return cStyleOnlineAssignment_3; }
		
		//StyleOnline
		public RuleCall getStyleOnlineStyleOnlineParserRuleCall_3_0() { return cStyleOnlineStyleOnlineParserRuleCall_3_0; }
		
		//(jsOnline=JSOnline)?
		public Assignment getJsOnlineAssignment_4() { return cJsOnlineAssignment_4; }
		
		//JSOnline
		public RuleCall getJsOnlineJSOnlineParserRuleCall_4_0() { return cJsOnlineJSOnlineParserRuleCall_4_0; }
		
		//elements+=Element+
		public Assignment getElementsAssignment_5() { return cElementsAssignment_5; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_5_0() { return cElementsElementParserRuleCall_5_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEDOMParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Element:
		//    Page | EDOM;
		@Override public ParserRule getRule() { return rule; }
		
		//Page | EDOM
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Page
		public RuleCall getPageParserRuleCall_0() { return cPageParserRuleCall_0; }
		
		//EDOM
		public RuleCall getEDOMParserRuleCall_1() { return cEDOMParserRuleCall_1; }
	}
	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSclassKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cHostclassesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cHostclassesStyleClassCrossReference_3_2_0 = (CrossReference)cHostclassesAssignment_3_2.eContents().get(0);
		private final RuleCall cHostclassesStyleClassIDTerminalRuleCall_3_2_0_1 = (RuleCall)cHostclassesStyleClassCrossReference_3_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Assignment cHomeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cHomeHomeKeyword_4_0 = (Keyword)cHomeAssignment_4.eContents().get(0);
		private final Assignment cShowInNavAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cShowInNavShowInNavKeyword_5_0 = (Keyword)cShowInNavAssignment_5.eContents().get(0);
		private final Assignment cPageFeaturesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPageFeaturesPageFeatureParserRuleCall_6_0 = (RuleCall)cPageFeaturesAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Page:
		//    'Page' name=ID
		//    '{'
		//    ('sclass' '{'(hostclasses+=[StyleClass])* '}')?
		//    (home?='home')?
		//    (showInNav?='showInNav')?
		//    (pageFeatures+=PageFeature)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Page' name=ID
		//'{'
		//('sclass' '{'(hostclasses+=[StyleClass])* '}')?
		//(home?='home')?
		//(showInNav?='showInNav')?
		//(pageFeatures+=PageFeature)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Page'
		public Keyword getPageKeyword_0() { return cPageKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('sclass' '{'(hostclasses+=[StyleClass])* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'sclass'
		public Keyword getSclassKeyword_3_0() { return cSclassKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//(hostclasses+=[StyleClass])*
		public Assignment getHostclassesAssignment_3_2() { return cHostclassesAssignment_3_2; }
		
		//[StyleClass]
		public CrossReference getHostclassesStyleClassCrossReference_3_2_0() { return cHostclassesStyleClassCrossReference_3_2_0; }
		
		//ID
		public RuleCall getHostclassesStyleClassIDTerminalRuleCall_3_2_0_1() { return cHostclassesStyleClassIDTerminalRuleCall_3_2_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_3() { return cRightCurlyBracketKeyword_3_3; }
		
		//(home?='home')?
		public Assignment getHomeAssignment_4() { return cHomeAssignment_4; }
		
		//'home'
		public Keyword getHomeHomeKeyword_4_0() { return cHomeHomeKeyword_4_0; }
		
		//(showInNav?='showInNav')?
		public Assignment getShowInNavAssignment_5() { return cShowInNavAssignment_5; }
		
		//'showInNav'
		public Keyword getShowInNavShowInNavKeyword_5_0() { return cShowInNavShowInNavKeyword_5_0; }
		
		//(pageFeatures+=PageFeature)*
		public Assignment getPageFeaturesAssignment_6() { return cPageFeaturesAssignment_6; }
		
		//PageFeature
		public RuleCall getPageFeaturesPageFeatureParserRuleCall_6_0() { return cPageFeaturesPageFeatureParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EDOMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.EDOM");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDOMParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCompParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStyleClassParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//EDOM:
		//    DOM | Comp | StyleClass ;
		@Override public ParserRule getRule() { return rule; }
		
		//DOM | Comp | StyleClass
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DOM
		public RuleCall getDOMParserRuleCall_0() { return cDOMParserRuleCall_0; }
		
		//Comp
		public RuleCall getCompParserRuleCall_1() { return cCompParserRuleCall_1; }
		
		//StyleClass
		public RuleCall getStyleClassParserRuleCall_2() { return cStyleClassParserRuleCall_2; }
	}
	public class StyleGlobalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.StyleGlobal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStyleGlobalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStyleGlobalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cStyleclassesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStyleclassesStyleClassParserRuleCall_3_0 = (RuleCall)cStyleclassesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//StyleGlobal:
		//    {StyleGlobal} 'StyleGlobal' '{'
		//        (styleclasses+=StyleClass)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{StyleGlobal} 'StyleGlobal' '{'
		//    (styleclasses+=StyleClass)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{StyleGlobal}
		public Action getStyleGlobalAction_0() { return cStyleGlobalAction_0; }
		
		//'StyleGlobal'
		public Keyword getStyleGlobalKeyword_1() { return cStyleGlobalKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(styleclasses+=StyleClass)*
		public Assignment getStyleclassesAssignment_3() { return cStyleclassesAssignment_3; }
		
		//StyleClass
		public RuleCall getStyleclassesStyleClassParserRuleCall_3_0() { return cStyleclassesStyleClassParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class StyleOnlineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.StyleOnline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStyleOnlineAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStyleOnlineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFullTagsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFullTagsSTRINGTerminalRuleCall_3_0 = (RuleCall)cFullTagsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//StyleOnline:
		//    {StyleOnline} 'StyleOnline' '{'
		//        (fullTags+=STRING)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{StyleOnline} 'StyleOnline' '{'
		//    (fullTags+=STRING)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{StyleOnline}
		public Action getStyleOnlineAction_0() { return cStyleOnlineAction_0; }
		
		//'StyleOnline'
		public Keyword getStyleOnlineKeyword_1() { return cStyleOnlineKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(fullTags+=STRING)*
		public Assignment getFullTagsAssignment_3() { return cFullTagsAssignment_3; }
		
		//STRING
		public RuleCall getFullTagsSTRINGTerminalRuleCall_3_0() { return cFullTagsSTRINGTerminalRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class JSOnlineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.JSOnline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cJSOnlineAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cJSOnlineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFullTagsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFullTagsSTRINGTerminalRuleCall_3_0 = (RuleCall)cFullTagsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//JSOnline:
		//    {JSOnline} 'JSOnline' '{'
		//        (fullTags+=STRING)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{JSOnline} 'JSOnline' '{'
		//    (fullTags+=STRING)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{JSOnline}
		public Action getJSOnlineAction_0() { return cJSOnlineAction_0; }
		
		//'JSOnline'
		public Keyword getJSOnlineKeyword_1() { return cJSOnlineKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(fullTags+=STRING)*
		public Assignment getFullTagsAssignment_3() { return cFullTagsAssignment_3; }
		
		//STRING
		public RuleCall getFullTagsSTRINGTerminalRuleCall_3_0() { return cFullTagsSTRINGTerminalRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class StyleClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.StyleClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStyleClassKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cSattributesAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cSattributesSAttributeAndValueParserRuleCall_3_0_0 = (RuleCall)cSattributesAssignment_3_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAfterKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Assignment cSattributesAfterAssignment_4_2_0 = (Assignment)cGroup_4_2.eContents().get(0);
		private final RuleCall cSattributesAfterSAttributeAndValueParserRuleCall_4_2_0_0 = (RuleCall)cSattributesAfterAssignment_4_2_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_2_1 = (Keyword)cGroup_4_2.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cActiveKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Assignment cSattributesActiveAssignment_5_2_0 = (Assignment)cGroup_5_2.eContents().get(0);
		private final RuleCall cSattributesActiveSAttributeAndValueParserRuleCall_5_2_0_0 = (RuleCall)cSattributesActiveAssignment_5_2_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2_1 = (Keyword)cGroup_5_2.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StyleClass:
		//    'StyleClass' name=Name
		//    '{'
		//        (sattributes+=SAttributeAndValue';')*
		//        ('after' '{'
		//            (sattributesAfter+=SAttributeAndValue';')*
		//        '}')?
		//        ('active' '{'
		//            (sattributesActive+=SAttributeAndValue';')*
		//        '}')?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'StyleClass' name=Name
		//'{'
		//    (sattributes+=SAttributeAndValue';')*
		//    ('after' '{'
		//        (sattributesAfter+=SAttributeAndValue';')*
		//    '}')?
		//    ('active' '{'
		//        (sattributesActive+=SAttributeAndValue';')*
		//    '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'StyleClass'
		public Keyword getStyleClassKeyword_0() { return cStyleClassKeyword_0; }
		
		//name=Name
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_1_0() { return cNameNameParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(sattributes+=SAttributeAndValue';')*
		public Group getGroup_3() { return cGroup_3; }
		
		//sattributes+=SAttributeAndValue
		public Assignment getSattributesAssignment_3_0() { return cSattributesAssignment_3_0; }
		
		//SAttributeAndValue
		public RuleCall getSattributesSAttributeAndValueParserRuleCall_3_0_0() { return cSattributesSAttributeAndValueParserRuleCall_3_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3_1() { return cSemicolonKeyword_3_1; }
		
		//('after' '{'
		//    (sattributesAfter+=SAttributeAndValue';')*
		//'}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'after'
		public Keyword getAfterKeyword_4_0() { return cAfterKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//(sattributesAfter+=SAttributeAndValue';')*
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//sattributesAfter+=SAttributeAndValue
		public Assignment getSattributesAfterAssignment_4_2_0() { return cSattributesAfterAssignment_4_2_0; }
		
		//SAttributeAndValue
		public RuleCall getSattributesAfterSAttributeAndValueParserRuleCall_4_2_0_0() { return cSattributesAfterSAttributeAndValueParserRuleCall_4_2_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4_2_1() { return cSemicolonKeyword_4_2_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_3() { return cRightCurlyBracketKeyword_4_3; }
		
		//('active' '{'
		//    (sattributesActive+=SAttributeAndValue';')*
		//'}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'active'
		public Keyword getActiveKeyword_5_0() { return cActiveKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//(sattributesActive+=SAttributeAndValue';')*
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//sattributesActive+=SAttributeAndValue
		public Assignment getSattributesActiveAssignment_5_2_0() { return cSattributesActiveAssignment_5_2_0; }
		
		//SAttributeAndValue
		public RuleCall getSattributesActiveSAttributeAndValueParserRuleCall_5_2_0_0() { return cSattributesActiveSAttributeAndValueParserRuleCall_5_2_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2_1() { return cSemicolonKeyword_5_2_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_3() { return cRightCurlyBracketKeyword_5_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SAttributeAndValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.SAttributeAndValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStnameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStnameNameParserRuleCall_0_0 = (RuleCall)cStnameAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRING2TerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//SAttributeAndValue:
		//    stname=Name value=STRING2
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//stname=Name value=STRING2
		public Group getGroup() { return cGroup; }
		
		//stname=Name
		public Assignment getStnameAssignment_0() { return cStnameAssignment_0; }
		
		//Name
		public RuleCall getStnameNameParserRuleCall_0_0() { return cStnameNameParserRuleCall_0_0; }
		
		//value=STRING2
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//STRING2
		public RuleCall getValueSTRING2TerminalRuleCall_1_0() { return cValueSTRING2TerminalRuleCall_1_0; }
	}
	public class DOMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.DOM");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDomKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cSclassKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cSclassesAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final CrossReference cSclassesStyleClassCrossReference_2_1_2_0 = (CrossReference)cSclassesAssignment_2_1_2.eContents().get(0);
		private final RuleCall cSclassesStyleClassIDTerminalRuleCall_2_1_2_0_1 = (RuleCall)cSclassesStyleClassCrossReference_2_1_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cSclassStringKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_2_1 = (Keyword)cGroup_2_2.eContents().get(1);
		private final Assignment cSclassesOnlineAssignment_2_2_2 = (Assignment)cGroup_2_2.eContents().get(2);
		private final RuleCall cSclassesOnlineSTRINGTerminalRuleCall_2_2_2_0 = (RuleCall)cSclassesOnlineAssignment_2_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2_3 = (Keyword)cGroup_2_2.eContents().get(3);
		private final Assignment cFeaturesAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cFeaturesFeatureParserRuleCall_2_3_0 = (RuleCall)cFeaturesAssignment_2_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//DOM:
		//    'Dom' name=ID
		//    ('{'
		//    ('sclass' '{'(sclasses+=[StyleClass])* '}')?
		//            ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//        (features+=Feature)*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Dom' name=ID
		//('{'
		//('sclass' '{'(sclasses+=[StyleClass])* '}')?
		//        ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//    (features+=Feature)*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'Dom'
		public Keyword getDomKeyword_0() { return cDomKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('{'
		//('sclass' '{'(sclasses+=[StyleClass])* '}')?
		//        ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//    (features+=Feature)*
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('sclass' '{'(sclasses+=[StyleClass])* '}')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'sclass'
		public Keyword getSclassKeyword_2_1_0() { return cSclassKeyword_2_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1_1() { return cLeftCurlyBracketKeyword_2_1_1; }
		
		//(sclasses+=[StyleClass])*
		public Assignment getSclassesAssignment_2_1_2() { return cSclassesAssignment_2_1_2; }
		
		//[StyleClass]
		public CrossReference getSclassesStyleClassCrossReference_2_1_2_0() { return cSclassesStyleClassCrossReference_2_1_2_0; }
		
		//ID
		public RuleCall getSclassesStyleClassIDTerminalRuleCall_2_1_2_0_1() { return cSclassesStyleClassIDTerminalRuleCall_2_1_2_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_1_3() { return cRightCurlyBracketKeyword_2_1_3; }
		
		//('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'sclassString'
		public Keyword getSclassStringKeyword_2_2_0() { return cSclassStringKeyword_2_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_2_1() { return cLeftCurlyBracketKeyword_2_2_1; }
		
		//(sclassesOnline+=STRING)*
		public Assignment getSclassesOnlineAssignment_2_2_2() { return cSclassesOnlineAssignment_2_2_2; }
		
		//STRING
		public RuleCall getSclassesOnlineSTRINGTerminalRuleCall_2_2_2_0() { return cSclassesOnlineSTRINGTerminalRuleCall_2_2_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_2_3() { return cRightCurlyBracketKeyword_2_2_3; }
		
		//(features+=Feature)*
		public Assignment getFeaturesAssignment_2_3() { return cFeaturesAssignment_2_3; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_2_3_0() { return cFeaturesFeatureParserRuleCall_2_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
	}
	public class CompElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.Comp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cSclassKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cHostclassesAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final CrossReference cHostclassesStyleClassCrossReference_2_1_2_0 = (CrossReference)cHostclassesAssignment_2_1_2.eContents().get(0);
		private final RuleCall cHostclassesStyleClassIDTerminalRuleCall_2_1_2_0_1 = (RuleCall)cHostclassesStyleClassCrossReference_2_1_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cSclassStringKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_2_1 = (Keyword)cGroup_2_2.eContents().get(1);
		private final Assignment cSclassesOnlineAssignment_2_2_2 = (Assignment)cGroup_2_2.eContents().get(2);
		private final RuleCall cSclassesOnlineSTRINGTerminalRuleCall_2_2_2_0 = (RuleCall)cSclassesOnlineAssignment_2_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2_3 = (Keyword)cGroup_2_2.eContents().get(3);
		private final Assignment cFeaturesAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cFeaturesFeatureParserRuleCall_2_3_0 = (RuleCall)cFeaturesAssignment_2_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//Comp:
		//    'Comp' name=ID
		//    (
		//    '{'
		//    ('sclass' '{'(hostclasses+=[StyleClass])* '}')?
		//        ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//        (features+=Feature)*
		//    '}'
		//    )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Comp' name=ID
		//(
		//'{'
		//('sclass' '{'(hostclasses+=[StyleClass])* '}')?
		//    ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//    (features+=Feature)*
		//'}'
		//)?
		public Group getGroup() { return cGroup; }
		
		//'Comp'
		public Keyword getCompKeyword_0() { return cCompKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//(
		//'{'
		//('sclass' '{'(hostclasses+=[StyleClass])* '}')?
		//    ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//    (features+=Feature)*
		//'}'
		//)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('sclass' '{'(hostclasses+=[StyleClass])* '}')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'sclass'
		public Keyword getSclassKeyword_2_1_0() { return cSclassKeyword_2_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1_1() { return cLeftCurlyBracketKeyword_2_1_1; }
		
		//(hostclasses+=[StyleClass])*
		public Assignment getHostclassesAssignment_2_1_2() { return cHostclassesAssignment_2_1_2; }
		
		//[StyleClass]
		public CrossReference getHostclassesStyleClassCrossReference_2_1_2_0() { return cHostclassesStyleClassCrossReference_2_1_2_0; }
		
		//ID
		public RuleCall getHostclassesStyleClassIDTerminalRuleCall_2_1_2_0_1() { return cHostclassesStyleClassIDTerminalRuleCall_2_1_2_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_1_3() { return cRightCurlyBracketKeyword_2_1_3; }
		
		//('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'sclassString'
		public Keyword getSclassStringKeyword_2_2_0() { return cSclassStringKeyword_2_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_2_1() { return cLeftCurlyBracketKeyword_2_2_1; }
		
		//(sclassesOnline+=STRING)*
		public Assignment getSclassesOnlineAssignment_2_2_2() { return cSclassesOnlineAssignment_2_2_2; }
		
		//STRING
		public RuleCall getSclassesOnlineSTRINGTerminalRuleCall_2_2_2_0() { return cSclassesOnlineSTRINGTerminalRuleCall_2_2_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_2_3() { return cRightCurlyBracketKeyword_2_2_3; }
		
		//(features+=Feature)*
		public Assignment getFeaturesAssignment_2_3() { return cFeaturesAssignment_2_3; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_2_3_0() { return cFeaturesFeatureParserRuleCall_2_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
	}
	public class InstanciaEDOMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.InstanciaEDOM");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInstanciaAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cInstanciaEDOMCrossReference_0_0 = (CrossReference)cInstanciaAssignment_0.eContents().get(0);
		private final RuleCall cInstanciaEDOMIDTerminalRuleCall_0_0_1 = (RuleCall)cInstanciaEDOMCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cSclassKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cSclassesAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final CrossReference cSclassesStyleClassCrossReference_1_1_2_0 = (CrossReference)cSclassesAssignment_1_1_2.eContents().get(0);
		private final RuleCall cSclassesStyleClassIDTerminalRuleCall_1_1_2_0_1 = (RuleCall)cSclassesStyleClassCrossReference_1_1_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_1_1_3 = (Keyword)cGroup_1_1.eContents().get(3);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cSclassStringKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_2_1 = (Keyword)cGroup_1_2.eContents().get(1);
		private final Assignment cSclassesOnlineAssignment_1_2_2 = (Assignment)cGroup_1_2.eContents().get(2);
		private final RuleCall cSclassesOnlineSTRINGTerminalRuleCall_1_2_2_0 = (RuleCall)cSclassesOnlineAssignment_1_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_2_3 = (Keyword)cGroup_1_2.eContents().get(3);
		private final Assignment cInsfeaturesAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cInsfeaturesInstanceEDOMFeatureParserRuleCall_1_3_0 = (RuleCall)cInsfeaturesAssignment_1_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		//InstanciaEDOM: instancia=[EDOM] ('{'
		//        ('sclass' '{'(sclasses+=[StyleClass])* '}')?
		//                ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//        (insfeatures+=InstanceEDOMFeature)*
		//    '}'
		//)?;
		@Override public ParserRule getRule() { return rule; }
		
		// instancia=[EDOM] ('{'
		//        ('sclass' '{'(sclasses+=[StyleClass])* '}')?
		//                ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//        (insfeatures+=InstanceEDOMFeature)*
		//    '}'
		//)?
		public Group getGroup() { return cGroup; }
		
		//instancia=[EDOM]
		public Assignment getInstanciaAssignment_0() { return cInstanciaAssignment_0; }
		
		//[EDOM]
		public CrossReference getInstanciaEDOMCrossReference_0_0() { return cInstanciaEDOMCrossReference_0_0; }
		
		//ID
		public RuleCall getInstanciaEDOMIDTerminalRuleCall_0_0_1() { return cInstanciaEDOMIDTerminalRuleCall_0_0_1; }
		
		// ('{'
		//        ('sclass' '{'(sclasses+=[StyleClass])* '}')?
		//                ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		//        (insfeatures+=InstanceEDOMFeature)*
		//    '}'
		//)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }
		
		//('sclass' '{'(sclasses+=[StyleClass])* '}')?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'sclass'
		public Keyword getSclassKeyword_1_1_0() { return cSclassKeyword_1_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_1_1() { return cLeftCurlyBracketKeyword_1_1_1; }
		
		//(sclasses+=[StyleClass])*
		public Assignment getSclassesAssignment_1_1_2() { return cSclassesAssignment_1_1_2; }
		
		//[StyleClass]
		public CrossReference getSclassesStyleClassCrossReference_1_1_2_0() { return cSclassesStyleClassCrossReference_1_1_2_0; }
		
		//ID
		public RuleCall getSclassesStyleClassIDTerminalRuleCall_1_1_2_0_1() { return cSclassesStyleClassIDTerminalRuleCall_1_1_2_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_1_3() { return cRightCurlyBracketKeyword_1_1_3; }
		
		//('sclassString' '{'(sclassesOnline+=STRING)* '}')?
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//'sclassString'
		public Keyword getSclassStringKeyword_1_2_0() { return cSclassStringKeyword_1_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_2_1() { return cLeftCurlyBracketKeyword_1_2_1; }
		
		//(sclassesOnline+=STRING)*
		public Assignment getSclassesOnlineAssignment_1_2_2() { return cSclassesOnlineAssignment_1_2_2; }
		
		//STRING
		public RuleCall getSclassesOnlineSTRINGTerminalRuleCall_1_2_2_0() { return cSclassesOnlineSTRINGTerminalRuleCall_1_2_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_2_3() { return cRightCurlyBracketKeyword_1_2_3; }
		
		//(insfeatures+=InstanceEDOMFeature)*
		public Assignment getInsfeaturesAssignment_1_3() { return cInsfeaturesAssignment_1_3; }
		
		//InstanceEDOMFeature
		public RuleCall getInsfeaturesInstanceEDOMFeatureParserRuleCall_1_3_0() { return cInsfeaturesInstanceEDOMFeatureParserRuleCall_1_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_4() { return cRightCurlyBracketKeyword_1_4; }
	}
	public class InstanceEDOMFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.InstanceEDOMFeature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cInstanciaEDOMAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cInstanciaEDOMInstanciaEDOMParserRuleCall_0_0 = (RuleCall)cInstanciaEDOMAssignment_0.eContents().get(0);
		private final Assignment cStringAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cStringSTRINGTerminalRuleCall_1_0 = (RuleCall)cStringAssignment_1.eContents().get(0);
		
		//InstanceEDOMFeature:
		//    instanciaEDOM=InstanciaEDOM  | string=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//instanciaEDOM=InstanciaEDOM  | string=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//instanciaEDOM=InstanciaEDOM
		public Assignment getInstanciaEDOMAssignment_0() { return cInstanciaEDOMAssignment_0; }
		
		//InstanciaEDOM
		public RuleCall getInstanciaEDOMInstanciaEDOMParserRuleCall_0_0() { return cInstanciaEDOMInstanciaEDOMParserRuleCall_0_0; }
		
		//string=STRING
		public Assignment getStringAssignment_1() { return cStringAssignment_1; }
		
		//STRING
		public RuleCall getStringSTRINGTerminalRuleCall_1_0() { return cStringSTRINGTerminalRuleCall_1_0; }
	}
	public class PageFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.PageFeature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cInstanciaEDOMAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cInstanciaEDOMInstanciaEDOMParserRuleCall_0_0 = (RuleCall)cInstanciaEDOMAssignment_0.eContents().get(0);
		private final Assignment cStringAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cStringSTRINGTerminalRuleCall_1_0 = (RuleCall)cStringAssignment_1.eContents().get(0);
		
		//PageFeature:
		//    instanciaEDOM=InstanciaEDOM |
		//    string=STRING ;
		@Override public ParserRule getRule() { return rule; }
		
		//instanciaEDOM=InstanciaEDOM |
		//string=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//instanciaEDOM=InstanciaEDOM
		public Assignment getInstanciaEDOMAssignment_0() { return cInstanciaEDOMAssignment_0; }
		
		//InstanciaEDOM
		public RuleCall getInstanciaEDOMInstanciaEDOMParserRuleCall_0_0() { return cInstanciaEDOMInstanciaEDOMParserRuleCall_0_0; }
		
		//string=STRING
		public Assignment getStringAssignment_1() { return cStringAssignment_1; }
		
		//STRING
		public RuleCall getStringSTRINGTerminalRuleCall_1_0() { return cStringSTRINGTerminalRuleCall_1_0; }
	}
	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.Feature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cInstanciaEDOMAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cInstanciaEDOMInstanciaEDOMParserRuleCall_0_0 = (RuleCall)cInstanciaEDOMAssignment_0.eContents().get(0);
		private final Assignment cAllowSlotAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cAllowSlotAllowSlotKeyword_1_0 = (Keyword)cAllowSlotAssignment_1.eContents().get(0);
		private final Assignment cStringAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cStringSTRINGTerminalRuleCall_2_0 = (RuleCall)cStringAssignment_2.eContents().get(0);
		
		//Feature:
		//    instanciaEDOM=InstanciaEDOM |
		//    AllowSlot?='AllowSlot' |
		//    string=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//instanciaEDOM=InstanciaEDOM |
		//AllowSlot?='AllowSlot' |
		//string=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//instanciaEDOM=InstanciaEDOM
		public Assignment getInstanciaEDOMAssignment_0() { return cInstanciaEDOMAssignment_0; }
		
		//InstanciaEDOM
		public RuleCall getInstanciaEDOMInstanciaEDOMParserRuleCall_0_0() { return cInstanciaEDOMInstanciaEDOMParserRuleCall_0_0; }
		
		//AllowSlot?='AllowSlot'
		public Assignment getAllowSlotAssignment_1() { return cAllowSlotAssignment_1; }
		
		//'AllowSlot'
		public Keyword getAllowSlotAllowSlotKeyword_1_0() { return cAllowSlotAllowSlotKeyword_1_0; }
		
		//string=STRING
		public Assignment getStringAssignment_2() { return cStringAssignment_2; }
		
		//STRING
		public RuleCall getStringSTRINGTerminalRuleCall_2_0() { return cStringSTRINGTerminalRuleCall_2_0; }
	}
	public class NameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.Name");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword c_Keyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cNumberSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cAsteriskKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cFullStopKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cColonColonKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cGreaterThanSignKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		private final RuleCall cIDTerminalRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Name:
		//     ('_'|'#'|'-'|'*'|'.'|'::'|'>'|ID)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('_'|'#'|'-'|'*'|'.'|'::'|'>'|ID)*
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'_'
		public Keyword get_Keyword_0() { return c_Keyword_0; }
		
		//'#'
		public Keyword getNumberSignKeyword_1() { return cNumberSignKeyword_1; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_2() { return cHyphenMinusKeyword_2; }
		
		//'*'
		public Keyword getAsteriskKeyword_3() { return cAsteriskKeyword_3; }
		
		//'.'
		public Keyword getFullStopKeyword_4() { return cFullStopKeyword_4; }
		
		//'::'
		public Keyword getColonColonKeyword_5() { return cColonColonKeyword_5; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_6() { return cGreaterThanSignKeyword_6; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_7() { return cIDTerminalRuleCall_7; }
	}
	
	
	private final RootElements pRoot;
	private final ElementElements pElement;
	private final PageElements pPage;
	private final EDOMElements pEDOM;
	private final StyleGlobalElements pStyleGlobal;
	private final StyleOnlineElements pStyleOnline;
	private final JSOnlineElements pJSOnline;
	private final StyleClassElements pStyleClass;
	private final SAttributeAndValueElements pSAttributeAndValue;
	private final DOMElements pDOM;
	private final CompElements pComp;
	private final InstanciaEDOMElements pInstanciaEDOM;
	private final InstanceEDOMFeatureElements pInstanceEDOMFeature;
	private final PageFeatureElements pPageFeature;
	private final FeatureElements pFeature;
	private final NameElements pName;
	private final TerminalRule tSTRING;
	private final TerminalRule tSTRING2;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public T2AGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRoot = new RootElements();
		this.pElement = new ElementElements();
		this.pPage = new PageElements();
		this.pEDOM = new EDOMElements();
		this.pStyleGlobal = new StyleGlobalElements();
		this.pStyleOnline = new StyleOnlineElements();
		this.pJSOnline = new JSOnlineElements();
		this.pStyleClass = new StyleClassElements();
		this.pSAttributeAndValue = new SAttributeAndValueElements();
		this.pDOM = new DOMElements();
		this.pComp = new CompElements();
		this.pInstanciaEDOM = new InstanciaEDOMElements();
		this.pInstanceEDOMFeature = new InstanceEDOMFeatureElements();
		this.pPageFeature = new PageFeatureElements();
		this.pFeature = new FeatureElements();
		this.pName = new NameElements();
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.STRING");
		this.tSTRING2 = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uma.es.angular.t2a.T2A.STRING2");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uma.es.angular.t2a.T2A".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Root:
	//    'AppName:' appName=STRING
	//    (globalStyle=StyleGlobal)?
	//    (styleOnline=StyleOnline)?
	//    (jsOnline=JSOnline)?
	//    elements+=Element+
	//;
	public RootElements getRootAccess() {
		return pRoot;
	}
	
	public ParserRule getRootRule() {
		return getRootAccess().getRule();
	}
	
	//Element:
	//    Page | EDOM;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Page:
	//    'Page' name=ID
	//    '{'
	//    ('sclass' '{'(hostclasses+=[StyleClass])* '}')?
	//    (home?='home')?
	//    (showInNav?='showInNav')?
	//    (pageFeatures+=PageFeature)*
	//    '}';
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}
	
	//EDOM:
	//    DOM | Comp | StyleClass ;
	public EDOMElements getEDOMAccess() {
		return pEDOM;
	}
	
	public ParserRule getEDOMRule() {
		return getEDOMAccess().getRule();
	}
	
	//StyleGlobal:
	//    {StyleGlobal} 'StyleGlobal' '{'
	//        (styleclasses+=StyleClass)*
	//    '}'
	//;
	public StyleGlobalElements getStyleGlobalAccess() {
		return pStyleGlobal;
	}
	
	public ParserRule getStyleGlobalRule() {
		return getStyleGlobalAccess().getRule();
	}
	
	//StyleOnline:
	//    {StyleOnline} 'StyleOnline' '{'
	//        (fullTags+=STRING)*
	//    '}'
	//;
	public StyleOnlineElements getStyleOnlineAccess() {
		return pStyleOnline;
	}
	
	public ParserRule getStyleOnlineRule() {
		return getStyleOnlineAccess().getRule();
	}
	
	//JSOnline:
	//    {JSOnline} 'JSOnline' '{'
	//        (fullTags+=STRING)*
	//    '}'
	//;
	public JSOnlineElements getJSOnlineAccess() {
		return pJSOnline;
	}
	
	public ParserRule getJSOnlineRule() {
		return getJSOnlineAccess().getRule();
	}
	
	//StyleClass:
	//    'StyleClass' name=Name
	//    '{'
	//        (sattributes+=SAttributeAndValue';')*
	//        ('after' '{'
	//            (sattributesAfter+=SAttributeAndValue';')*
	//        '}')?
	//        ('active' '{'
	//            (sattributesActive+=SAttributeAndValue';')*
	//        '}')?
	//    '}'
	//;
	public StyleClassElements getStyleClassAccess() {
		return pStyleClass;
	}
	
	public ParserRule getStyleClassRule() {
		return getStyleClassAccess().getRule();
	}
	
	//SAttributeAndValue:
	//    stname=Name value=STRING2
	//;
	public SAttributeAndValueElements getSAttributeAndValueAccess() {
		return pSAttributeAndValue;
	}
	
	public ParserRule getSAttributeAndValueRule() {
		return getSAttributeAndValueAccess().getRule();
	}
	
	//DOM:
	//    'Dom' name=ID
	//    ('{'
	//    ('sclass' '{'(sclasses+=[StyleClass])* '}')?
	//            ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
	//        (features+=Feature)*
	//    '}')?;
	public DOMElements getDOMAccess() {
		return pDOM;
	}
	
	public ParserRule getDOMRule() {
		return getDOMAccess().getRule();
	}
	
	//Comp:
	//    'Comp' name=ID
	//    (
	//    '{'
	//    ('sclass' '{'(hostclasses+=[StyleClass])* '}')?
	//        ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
	//        (features+=Feature)*
	//    '}'
	//    )?
	//;
	public CompElements getCompAccess() {
		return pComp;
	}
	
	public ParserRule getCompRule() {
		return getCompAccess().getRule();
	}
	
	//InstanciaEDOM: instancia=[EDOM] ('{'
	//        ('sclass' '{'(sclasses+=[StyleClass])* '}')?
	//                ('sclassString' '{'(sclassesOnline+=STRING)* '}')?
	//        (insfeatures+=InstanceEDOMFeature)*
	//    '}'
	//)?;
	public InstanciaEDOMElements getInstanciaEDOMAccess() {
		return pInstanciaEDOM;
	}
	
	public ParserRule getInstanciaEDOMRule() {
		return getInstanciaEDOMAccess().getRule();
	}
	
	//InstanceEDOMFeature:
	//    instanciaEDOM=InstanciaEDOM  | string=STRING;
	public InstanceEDOMFeatureElements getInstanceEDOMFeatureAccess() {
		return pInstanceEDOMFeature;
	}
	
	public ParserRule getInstanceEDOMFeatureRule() {
		return getInstanceEDOMFeatureAccess().getRule();
	}
	
	//PageFeature:
	//    instanciaEDOM=InstanciaEDOM |
	//    string=STRING ;
	public PageFeatureElements getPageFeatureAccess() {
		return pPageFeature;
	}
	
	public ParserRule getPageFeatureRule() {
		return getPageFeatureAccess().getRule();
	}
	
	//Feature:
	//    instanciaEDOM=InstanciaEDOM |
	//    AllowSlot?='AllowSlot' |
	//    string=STRING
	//;
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}
	
	//Name:
	//     ('_'|'#'|'-'|'*'|'.'|'::'|'>'|ID)*
	//;
	public NameElements getNameAccess() {
		return pName;
	}
	
	public ParserRule getNameRule() {
		return getNameAccess().getRule();
	}
	
	//@Override
	//terminal STRING:
	//    '"' ( '\\'('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\') | !('\\'|'"') )* '"' |
	//    "'" ( '\\'('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\') | !('\\'|"'") )* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal STRING2:
	//    (': '|':'|' : ')('a'..'z'|'A'..'Z'|'0'..'9'|'_'|'#'|'-'|'%'|'*'|','|', '|'('|')'|'px '|'"') ('a'..'z'|'A'..'Z'|'_'|'0'..'9'|'#'|'-'|'%'|'*'|','|', '|'('|')'|'px '|'"')*;
	public TerminalRule getSTRING2Rule() {
		return tSTRING2;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
