/*
 * generated by Xtext 2.31.0
 */
package uma.es.angular.t2a.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class T2AValidator extends AbstractT2AValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					T2APackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
