/*
 * generated by Xtext 2.31.0
 */
package uma.es.angular.t2a.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractT2AScopeProvider extends DelegatingScopeProvider {
}
