/**
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.t2A.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import uma.es.angular.t2a.t2A.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see uma.es.angular.t2a.t2A.T2APackage
 * @generated
 */
public class T2ASwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static T2APackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public T2ASwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = T2APackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case T2APackage.ROOT:
      {
        Root root = (Root)theEObject;
        T result = caseRoot(root);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.ELEMENT:
      {
        Element element = (Element)theEObject;
        T result = caseElement(element);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.PAGE:
      {
        Page page = (Page)theEObject;
        T result = casePage(page);
        if (result == null) result = caseElement(page);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.EDOM:
      {
        EDOM edom = (EDOM)theEObject;
        T result = caseEDOM(edom);
        if (result == null) result = caseElement(edom);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.STYLE_GLOBAL:
      {
        StyleGlobal styleGlobal = (StyleGlobal)theEObject;
        T result = caseStyleGlobal(styleGlobal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.STYLE_ONLINE:
      {
        StyleOnline styleOnline = (StyleOnline)theEObject;
        T result = caseStyleOnline(styleOnline);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.JS_ONLINE:
      {
        JSOnline jsOnline = (JSOnline)theEObject;
        T result = caseJSOnline(jsOnline);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.STYLE_CLASS:
      {
        StyleClass styleClass = (StyleClass)theEObject;
        T result = caseStyleClass(styleClass);
        if (result == null) result = caseEDOM(styleClass);
        if (result == null) result = caseElement(styleClass);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.SATTRIBUTE_AND_VALUE:
      {
        SAttributeAndValue sAttributeAndValue = (SAttributeAndValue)theEObject;
        T result = caseSAttributeAndValue(sAttributeAndValue);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.DOM:
      {
        DOM dom = (DOM)theEObject;
        T result = caseDOM(dom);
        if (result == null) result = caseEDOM(dom);
        if (result == null) result = caseElement(dom);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.COMP:
      {
        Comp comp = (Comp)theEObject;
        T result = caseComp(comp);
        if (result == null) result = caseEDOM(comp);
        if (result == null) result = caseElement(comp);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.INSTANCIA_EDOM:
      {
        InstanciaEDOM instanciaEDOM = (InstanciaEDOM)theEObject;
        T result = caseInstanciaEDOM(instanciaEDOM);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.INSTANCE_EDOM_FEATURE:
      {
        InstanceEDOMFeature instanceEDOMFeature = (InstanceEDOMFeature)theEObject;
        T result = caseInstanceEDOMFeature(instanceEDOMFeature);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.PAGE_FEATURE:
      {
        PageFeature pageFeature = (PageFeature)theEObject;
        T result = casePageFeature(pageFeature);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case T2APackage.FEATURE:
      {
        Feature feature = (Feature)theEObject;
        T result = caseFeature(feature);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Root</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Root</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRoot(Root object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseElement(Element object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Page</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Page</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePage(Page object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EDOM</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EDOM</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEDOM(EDOM object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Style Global</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Style Global</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStyleGlobal(StyleGlobal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Style Online</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Style Online</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStyleOnline(StyleOnline object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>JS Online</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>JS Online</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseJSOnline(JSOnline object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Style Class</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Style Class</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStyleClass(StyleClass object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>SAttribute And Value</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>SAttribute And Value</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSAttributeAndValue(SAttributeAndValue object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>DOM</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>DOM</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDOM(DOM object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Comp</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Comp</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComp(Comp object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Instancia EDOM</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Instancia EDOM</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInstanciaEDOM(InstanciaEDOM object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Instance EDOM Feature</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Instance EDOM Feature</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInstanceEDOMFeature(InstanceEDOMFeature object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Page Feature</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Page Feature</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePageFeature(PageFeature object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Feature</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Feature</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFeature(Feature object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //T2ASwitch
