/*
 * generated by Xtext 2.26.0
 */
package uma.es.angular.t2a.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class T2AScopeProvider extends AbstractT2AScopeProvider {

}
